.\" Manpage for slockd.
.\" Contact me@risto.codes
.TH man 1 "11 June 2023" "1.0" "slockd man page"
.SH NAME
slockd runit service
.SH SYNOPSIS
sv start slockd
.SH DESCRIPTION
An runit service to run slock on idle or sleep
.SH OPTIONS
NA
.SH SEE ALSO
sv(8), runsvdir(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Risto Stevcev (me@risto.codes)
