#!/bin/sh
exec 2>&1
exec chpst -u risto ./i3lockd.sh

#DISPALY=:0
#XAUTHORITY=/run/user/1000/gdm/Xauthority
#exec runuser -u risto -- xss-lock --transfer-sleep-lock -- xautolock -time 15 -locker 'i3lock --nofork'
#exec xss-lock --transfer-sleep-lock -- xautolock -time 15 -locker 'i3lock --nofork'
